spring:
  application:
    name: reward-service
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/reward_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
    driver-class-name: org.postgresql.Driver

  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    metadata-map:
      management:
        port: 8082

logging:
  level:
    org.springframework.cloud: DEBUG
    com.zaxxer.hikari: TRACE

security:
  jwt:
    secret: "MaCleSuperSecreteQuiFaitPlusDe32Caractères1234"
    expiration: 3600000

#profil local
gateway:
  url: http://localhost:8222

---

#profil docker
spring:
  config:
    activate:
      on-profile: docker

gateway:
  url: http://gateway-service:8222