server:
  port: 8083

spring:
  application:
    name: reward-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: false
    hostname: reward-service

logging:
  level:
    root: INFO
    com.Quiz.reward: DEBUG