spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  profiles:
    active: native

server:
  port: 8888
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info
